# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OctopusCli < Formula
  desc "The New CLI (octopus) for Octopus Deploy, a user-friendly DevOps tool for developers that supports release management, deployment automation, and operations runbooks"
  homepage "https://github.com/OctopusDeploy/cli"
  version "2.14.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OctopusDeploy/cli/releases/download/v2.14.2/octopus_2.14.2_macOS_amd64.tar.gz"
      sha256 "02433ed2c35bcd706daa6d0b3bb09b97b8ae4ffa9861c114ff7ac82650c42733"

      def install
        bin.install "octopus"
        # future: enhance the CLI to generate completion scripts, and install them as follows
        # bash_completion.install "completions/octopus.bash" => "octopus"
        # zsh_completion.install "completions/octopus.zsh" => "_octopus"
        # fish_completion.install "completions/octopus.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OctopusDeploy/cli/releases/download/v2.14.2/octopus_2.14.2_macOS_arm64.tar.gz"
      sha256 "a9318e2e41f2129de5529574e020306c197a8393a6cdf5c7ad7babc1c2d5de5e"

      def install
        bin.install "octopus"
        # future: enhance the CLI to generate completion scripts, and install them as follows
        # bash_completion.install "completions/octopus.bash" => "octopus"
        # zsh_completion.install "completions/octopus.zsh" => "_octopus"
        # fish_completion.install "completions/octopus.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OctopusDeploy/cli/releases/download/v2.14.2/octopus_2.14.2_linux_amd64.tar.gz"
        sha256 "26ecc2ac4a115bdb20998d0dc47e755ff0679cc78df4f869c80af05b60c7d8e1"

        def install
          bin.install "octopus"
          # future: enhance the CLI to generate completion scripts, and install them as follows
          # bash_completion.install "completions/octopus.bash" => "octopus"
          # zsh_completion.install "completions/octopus.zsh" => "_octopus"
          # fish_completion.install "completions/octopus.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OctopusDeploy/cli/releases/download/v2.14.2/octopus_2.14.2_linux_arm64.tar.gz"
        sha256 "ce72a6a89ea859086a827243dc29a243f15b3e102edea7c8ec12668d0cc8c47a"

        def install
          bin.install "octopus"
          # future: enhance the CLI to generate completion scripts, and install them as follows
          # bash_completion.install "completions/octopus.bash" => "octopus"
          # zsh_completion.install "completions/octopus.zsh" => "_octopus"
          # fish_completion.install "completions/octopus.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/octopus", "--help"
  end
end
