# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OctopusCli < Formula
  desc "The New CLI (octopus) for Octopus Deploy, a user-friendly DevOps tool for developers that supports release management, deployment automation, and operations runbooks"
  homepage "https://github.com/OctopusDeploy/cli"
  version "2.14.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OctopusDeploy/cli/releases/download/v2.14.3/octopus_2.14.3_macOS_amd64.tar.gz"
      sha256 "fa292855150037bcde065d99d8c5578cff94a7aac905a685654d4c020975a108"

      def install
        bin.install "octopus"
        # future: enhance the CLI to generate completion scripts, and install them as follows
        # bash_completion.install "completions/octopus.bash" => "octopus"
        # zsh_completion.install "completions/octopus.zsh" => "_octopus"
        # fish_completion.install "completions/octopus.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OctopusDeploy/cli/releases/download/v2.14.3/octopus_2.14.3_macOS_arm64.tar.gz"
      sha256 "f402a50e336b24e994bf33b667785905ce9e3b717f69c9a4a1631bfb2b0ab791"

      def install
        bin.install "octopus"
        # future: enhance the CLI to generate completion scripts, and install them as follows
        # bash_completion.install "completions/octopus.bash" => "octopus"
        # zsh_completion.install "completions/octopus.zsh" => "_octopus"
        # fish_completion.install "completions/octopus.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OctopusDeploy/cli/releases/download/v2.14.3/octopus_2.14.3_linux_amd64.tar.gz"
        sha256 "4993a43da82b86640c7a72e8ec36204ec54b4556306c1647835d306107f482c6"

        def install
          bin.install "octopus"
          # future: enhance the CLI to generate completion scripts, and install them as follows
          # bash_completion.install "completions/octopus.bash" => "octopus"
          # zsh_completion.install "completions/octopus.zsh" => "_octopus"
          # fish_completion.install "completions/octopus.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OctopusDeploy/cli/releases/download/v2.14.3/octopus_2.14.3_linux_arm64.tar.gz"
        sha256 "7aac4b68e18f20483b01168ec07ed2b3f1a7c67098303890c06e9dc176c02c6d"

        def install
          bin.install "octopus"
          # future: enhance the CLI to generate completion scripts, and install them as follows
          # bash_completion.install "completions/octopus.bash" => "octopus"
          # zsh_completion.install "completions/octopus.zsh" => "_octopus"
          # fish_completion.install "completions/octopus.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/octopus", "--help"
  end
end
