name: "Release Update Approve and Auto Merge"

on:
  push:
    branches: 
      - 'releases/**'

  pull_request:
    branches: 
      - $default-branch

# Increase the access for the GITHUB_TOKEN
permissions:
  # This Allows the GITHUB_TOKEN to approve pull requests
  pull-requests: write
  # This Allows the GITHUB_TOKEN to auto merge pull requests
  contents: write

env:
  GITHUB_TOKEN: ${{secrets.INTEGRATIONS_FNM_BOT_TOKEN}}
  GH_TOKEN: ${{secrets.INTEGRATIONS_FNM_BOT_TOKEN}}

jobs:
  create-pr-for-update:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.actor == 'team-integrations-fnm-bot' }}

    steps:
      - uses: actions/checkout@v3

      - name: Create PR
        run: gh pr create --title "Publish new CLI release to homebrew" --body "This is an automated PR, it should be auto-merged if checks are green."

  pr-auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.actor == 'team-integrations-fnm-bot' }}

    env:
      PR_URL: ${{github.event.pull_request.html_url}}

    steps:
      - uses: actions/checkout@v3

      - name: Enable auto-merge for release update PRs
        run: gh pr merge --auto --squash "$PR_URL"